services:
  - type: web
    name: tapping-agent
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: NOSTR_PRIVATE_KEY
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: ENABLE_CKB_BOT
        value: "true"
      - key: ENABLE_NOSTR
        value: "true"
    autoDeploy: true 